version: "3.9"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 3001:3001

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
